[WIP]ホテル検索ページの見た目を実装する
mzw86020424/next-rakuten-app pull request #22
Opened 2023-04-15 06:19 UTC by mzw86020424

## イシュー番号
* Fix #3

## やったこと
* このプルリクで何をしたのか？

## やらないこと
* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）（やらない場合は、いつやるのかを明記する。）

## できるようになること（ユーザ目線）
* 何ができるようになるのか？（あれば。無いなら「無し」でOK）

## できなくなること（ユーザ目線）
* 何ができなくなるのか？（あれば。無いなら「無し」でOK）

## チェック項目
 - [ ] `npm run lint`でエラーがでないことを確認

## 動作確認
* どのような動作確認を行ったのか？　結果はどうか？

## その他
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2023-04-15 14:14 UTC, mzw86020424 commented on app/pages/hotels.tsx
> +  const [searchTerm, setSearchTerm] = useState('');
グローバルに状態を持たせる必要があるかどうかは今後検討

2023-04-15 14:15 UTC, mzw86020424 commented on app/styles/globals.css
> +html,
cssは適当に書いただけだからサラッとみてくれればOKだよ

2023-04-16 06:17 UTC, tkm-mkzk commented on app/styles/globals.css
> +html,
@mzw86020424 
テストコードほしいっすね！

2023-04-17 06:48 UTC, tkm-mkzk commented
@mzw86020424 
vercelのデプロイエラー起きてません？

2023-04-17 07:19 UTC, mzw86020424 commented
> @mzw86020424 
> vercelのデプロイエラー起きてません？

テスト通ってないからエラーになってるので後で直すよ！待ってね！

2023-04-17 07:53 UTC, tkm-mkzk commented
@mzw86020424 
まだ途中ってことですね！早とちりました！

2023-04-17 14:08 UTC, mzw86020424 commented
> @mzw86020424 まだ途中ってことですね！早とちりました！

これローカルでjest実行してもエラーでないんだけど、このブランチpullして試してもらってもいい？

2023-04-17 14:39 UTC, mzw86020424 commented on app/styles/globals.css
> +html,
@tkm-mkzk 
レビューした後変更してほしい時はrequest changesするといいよ！
https://qiita.com/YumaInaura/items/8223add6d8335a2eda7f
そしたらこっちが修正後に再レビュー依頼出せるようになるから！

2023-04-17 23:32 UTC, tkm-mkzk requested changes
test

2023-04-17 23:59 UTC, tkm-mkzk requested changes
@mzw86020424 
コメントシヤした！

2023-04-17 23:59 UTC, tkm-mkzk commented on app/components/__tests__/hotels.tsx
__tests__フォルダをpages配下にも作って、そっちに移したほうが良いかもですね！pages配下のファイルはpages/__tests__にテスト書いて、components配下にはcomponents/__tests__にテスト書く感じです！

2023-04-18 00:01 UTC, mzw86020424 commented on app/components/__tests__/hotels.tsx
元の実装はそうしてたけど、それだとデプロイエラー起こすからそこに移したのよ！コミット履歴と参考に貼った記事見てみて🙋‍♂️

2023-04-18 00:09 UTC, tkm-mkzk commented on app/components/__tests__/hotels.tsx
@mzw86020424 
記事見ました！なんかもっときれいにテストファイル整理できる方法探してます！

2023-04-18 00:11 UTC, mzw86020424 commented on app/components/__tests__/hotels.tsx
そもそもコンポーンネントとかページズ配下にいなくても読み込めてるぽいから、ルート配下にテスト用ディレクトリでも良さそうな気がするね！

2023-04-18 00:14 UTC, tkm-mkzk commented on app/components/__tests__/hotels.tsx
@mzw86020424 
なんかさっきissue作ったんですけど、基本srcフォルダにpages,components,stylesをまとめるのが、一般的みたいなので、そこにtestsフォルダ作ってまとめるってのが良さそうじゃないですか？

2023-04-18 00:15 UTC, tkm-mkzk commented on app/components/__tests__/hotels.tsx
@mzw86020424 
そしたら一旦ルート配下にテストフォルダ移しますか！

2023-04-18 23:43 UTC, mzw86020424 commented on app/components/__tests__/hotels.tsx
[465264b](https://github.com/mzw86020424/next-rakuten-app/pull/22/commits/465264bf4db1b6529cb484f553d0e5c12518fb59)こちらで修正しました！

2023-04-19 00:03 UTC, tkm-mkzk approved these changes

2023-04-19 00:05 UTC, tkm-mkzk commented
![lgtm](https://user-images.githubusercontent.com/71067058/232930450-382f85b1-d6c1-40b6-8a16-5a57998acb14.jpeg)
@mzw86020424

2023-04-19 00:22 UTC, merged