:seedling: start creating railsapi class / make rails api process com…
mzw86020424/next-rakuten-app pull request #77
Opened 2023-07-31 00:08 UTC by mzw86020424

…mon / #74

## イシュー番号
* Fix #00

## やったこと
* このプルリクで何をしたのか？

## やらないこと
* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）（やらない場合は、いつやるのかを明記する。）

## できるようになること（ユーザ目線）
* 何ができるようになるのか？（あれば。無いなら「無し」でOK）

## できなくなること（ユーザ目線）
* 何ができなくなるのか？（あれば。無いなら「無し」でOK）

## チェック項目
 - [ ] `npm run lint`でエラーがでないことを確認
 - [ ] `rubocop -A`で整形されたことを確認
 - [ ] `rspec`でテストが通ることを確認

## 動作確認
* どのような動作確認を行ったのか？　結果はどうか？

## その他
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2023-08-03 00:13 UTC, mzw86020424 commented on frontend/services/rakutenApi.ts
> -  const appId = process.env.NEXT_PUBLIC_RAKUTEN_ID
このPRと直接関係ないがappIdが参照されていなかったので削除

2023-08-06 04:38 UTC, mzw86020424 commented on frontend/.env.sample
> +NEXT_PUBLIC_RAILS_API_URL=
共有されてたけどsampleに入ってなかったので追加

2023-08-13 02:08 UTC, tkm-mkzk commented
@mzw86020424 
envファイルのせいかもしれないですが、Searchボタン押しても結果表示されないです。

2023-08-13 02:08 UTC, tkm-mkzk requested changes

2023-08-13 02:08 UTC, tkm-mkzk commented on frontend/.env.sample
> +NEXT_PUBLIC_RAILS_API_URL=
@mzw86020424 
slackのenv共有と内容ずれてません？今envファイルどうなっていますか？

2023-08-13 10:24 UTC, mzw86020424 commented
> @mzw86020424 envファイルのせいかもしれないですが、Searchボタン押しても結果表示されないです。

@tkm-mkzk 
コンソールエラー出てると思うのでスクショ共有してもらえる？

2023-08-13 23:16 UTC, mzw86020424 commented
> > @mzw86020424 envファイルのせいかもしれないですが、Searchボタン押しても結果表示されないです。
> 
> @tkm-mkzk コンソールエラー出てると思うのでスクショ共有してもらえる？

@tkm-mkzk 
[b3389ae](https://github.com/mzw86020424/next-rakuten-app/pull/77/commits/b3389ae4390f1246f0ba9d051f65d63c241a020b) で直しました！

2023-08-13 23:50 UTC, tkm-mkzk commented on frontend/.env.sample
> +NEXT_PUBLIC_RAILS_API_URL=
@mzw86020424 
ここも修正してもらえると！

2023-08-14 00:15 UTC, mzw86020424 commented on frontend/.env.sample
> +NEXT_PUBLIC_RAILS_API_URL=
@tkm-mkzk 
[49439aa](https://github.com/mzw86020424/next-rakuten-app/pull/77/commits/49439aaf00456f2befaeebda162d0b4b91575d12)で直しました！

2023-08-27 05:31 UTC, tkm-mkzk approved these changes
LGTMです！

2023-08-27 05:31 UTC, merged