[wip]:sparkles: Add thumbnail images to hotel list for UX improvement/#70
mzw86020424/next-rakuten-app pull request #79
Opened 2023-08-05 04:31 UTC by tkm-mkzk

## イシュー番号
* Fix #70 

## やったこと
* UX向上のため、ホテル一覧にサムネイル画像の列を一列目に追加した

## やらないこと
* なし

## できるようになること（ユーザ目線）
* ホテル検索の際、画像によりホテルのイメージを視覚的に知ることができるようになる。

## できなくなること（ユーザ目線）
* なし

## チェック項目
 - [ ] `npm run lint`でエラーがでないことを確認
 - [ ] `rubocop -A`で整形されたことを確認
 - [ ] `rspec`でテストが通ることを確認

## 動作確認
* ど

## その他
* next.config.jsの内容を変更したため、dockerを立ち上げ直して確認してください。

2023-08-06 01:46 UTC, mzw86020424 requested changes

2023-08-06 01:46 UTC, mzw86020424 commented on frontend/pages/hotels.tsx
> +                      height={200}
高さの制御が効いてないみたい！てか高さの制御なくても良さそう

2023-08-06 05:04 UTC, tkm-mkzk commented on frontend/pages/hotels.tsx
> +                      height={200}
@mzw86020424 
https://dev.classmethod.jp/articles/next-js-image-component/

2023-08-06 05:23 UTC, tkm-mkzk commented on frontend/pages/hotels.tsx
> +                      height={200}
@tkm-mkzk 
上記参考に画像表示サイズ変更したので、レビューお願いします！！！！！

2023-08-07 00:12 UTC, mzw86020424 commented on frontend/pages/hotels.tsx
> +                      height={200}
@tkm-mkzk 
サイズはいいと思います！

2023-08-08 00:10 UTC, tkm-mkzk commented on frontend/pages/hotels.tsx
> +                      height={200}
@mzw86020424 
hotelThumbnailUrlも試したんですけどすごい画質粗いんですよね。ただ、実際にお客さんいるわけじゃないので、一旦サムネイルの方にします！

2023-08-09 00:05 UTC, mzw86020424 commented on frontend/pages/hotels.tsx
> +                      height={200}
@tkm-mkzk 
そもそもだけどサムネイルを画質上げる必要はなくて（小さくて早く表示させるためのものなので）、ページ速度を上げてユーザー体験良くするためにもそっちの方が適切だと思います！

2023-08-09 00:07 UTC, mzw86020424 approved these changes
lgtmです！ちなみにImageタグはwidthとheightなくてもいけたの？

2023-08-09 00:31 UTC, tkm-mkzk commented
@mzw86020424 

> lgtmです！ちなみにImageタグはwidthとheightなくてもいけたの？

```
className="object-cover"
fill
```

この記述がかわりのやつです！

2023-08-09 00:32 UTC, merged

2023-08-09 00:33 UTC, tkm-mkzk commented on frontend/pages/hotels.tsx
> +                      height={200}
@mzw86020424 
ちなみに想像以上に粗いですよ！

2023-08-11 00:29 UTC, mzw86020424 commented on frontend/pages/hotels.tsx
> +                      height={200}
@tkm-mkzk 
https://travel.rakuten.co.jp/ranking/9_0007_0_0_0_0.html
大体こんくらいよ！