#71 Postモデルにバリデーションを追加
mzw86020424/next-rakuten-app pull request #81
Opened 2023-08-06 02:34 UTC by tkm-mkzk

## イシュー番号
* Fix #71 

## やったこと
* Postモデルに文字数制限のバリデーションを追加
* 上記に関するRSpecの追加

## やらないこと
* フロント側の処理関連

## できるようになること（ユーザ目線）
* なし

## できなくなること（ユーザ目線）
* ブログ投稿でtitleが51文字、captionが101文字以上の投稿ができなくなる

## チェック項目
 - [ ] `npm run lint`でエラーがでないことを確認
 - [ ] `rubocop -A`で整形されたことを確認
 - [ ] `rspec`でテストが通ることを確認

## 動作確認
* rspec spec/models/post_spec.rbの実行にてエラーがでないこと
* rails cにてブログ投稿でtitleが51文字、captionが101文字以上の投稿でバリデーションエラーが発生すること

## その他
* なし

2023-08-06 04:11 UTC, mzw86020424 requested changes

2023-08-06 04:11 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +    end
[must]postモデルをテストするのでuserを作る必要はないと思います！（純粋なpostのテストにならない）

2023-08-07 00:24 UTC, mzw86020424 requested changes

2023-08-07 00:24 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +      post = Post.new(title: 'a' * 51)
rspecでは基本的にletを使って定義してください！

2023-08-07 00:24 UTC, mzw86020424 commented on api/app/models/user.rb
> +  validates :sub, presence: true
これのテストもお願いします！

2023-08-08 23:49 UTC, mzw86020424 requested changes

2023-08-08 23:49 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +    let(:post) { Post.new(user: user, title: title_content, caption: caption_content) }
[imo]
letで定義したuserはその後使われないので以下の書き方でもいいと思います。
```
let(:post) { Post.new(user: create(:user), title: title_content, caption: caption_content) }
```

2023-08-08 23:49 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
[ask]各contextのこの記述が不要に見えるけど、入れた意図を教えてもらってもいい？？

2023-08-09 00:39 UTC, tkm-mkzk commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
@mzw86020424 
それぞれのテストを項目ごとにグルーブ分けしたほうが分かりやすいと思うからです！

2023-08-09 23:32 UTC, tkm-mkzk commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
@mzw86020424 
contextがいらないって言っているのかと勘違いしてました！
let(:caption_content) { 'a' * 100 } 
これを入れた理由としては
let(:post) { Post.new(user: user, title: title_content, caption: caption_content) }
これを呼び出すときに必要になるからです！
 let(:caption_content) { 'a' * 100 }
この記述ないとrspecが失敗します。

2023-08-11 00:22 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
@tkm-mkzk 
個別のケースで何を試す必要があるのかを考慮した上で以下を検討してもらえるといいかも！
1. そのpostはtitleやcaptionを定義する必要があるか？
2. そのpostはその場所で定義されるのが適切なのか？

2023-08-13 10:45 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
@tkm-mkzk 
[1dfe5b8](https://github.com/mzw86020424/next-rakuten-app/pull/81/commits/1dfe5b8807858f3c4f487baa98d63c9bafd2e2cc)で修正しましたー！あくまで１つのやり方なだけなので他の方法が良ければ修正してね！

2023-08-13 23:39 UTC, tkm-mkzk commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
@mzw86020424 
ありがとうございます！
あーフロントエンド側でtitileとcaption必須にしてたんで、てっきり、バックエンド側でも必須だと勘違いしてました。postsテーブルのtitleとcaptionは必須項目の設定してなかったんですね。してあると思ってテスト書いてました！

そうなるとバックエンド側もモデルとデータベースも修正したほうがよいかもしれないと思いました！

2023-08-14 00:05 UTC, mzw86020424 commented on api/spec/models/post_spec.rb
> +      let(:caption_content) { 'a' * 100 } # 複数のテストで再利用されるためデフォルトとして設定
@tkm-mkzk 
必須に寄せるということであれば別イシューきって対応お願いします！

2023-08-27 05:18 UTC, mzw86020424 approved these changes

2023-08-27 05:20 UTC, merged