rubocopのカスタマイズ/#80
mzw86020424/next-rakuten-app pull request #83
Opened 2023-08-07 00:09 UTC by tkm-mkzk

## イシュー番号
* Fix #80 

## やったこと
* rubocopが厳しすぎるため、ルールを緩めに設定

## やらないこと
* なし

## できるようになること（ユーザ目線）
* なし

## できなくなること（ユーザ目線）
* なし

## チェック項目
 - [ ] `npm run lint`でエラーがでないことを確認
 - [ ] `rubocop -A`で整形されたことを確認
 - [ ] `rspec`でテストが通ることを確認

## 動作確認
* なし

## その他
* なし

2023-08-07 00:12 UTC, tkm-mkzk commented
@mzw86020424 
いろいろ参考に一旦rubocopカスタマイズしてみました。これでも違反で引っかかる場合は各自ルール確認して、必要ならコード修正、ルールが厳しすぎると感じたら、その都度修正するのが良さそうです。

2023-08-07 00:20 UTC, mzw86020424 requested changes

2023-08-07 00:20 UTC, mzw86020424 commented on api/.rubocop.yml
> +  Enabled: false
これはあってもいいと思う

2023-08-07 00:20 UTC, mzw86020424 commented on api/.rubocop.yml
> +Style/ClassAndModuleChildren:
Hoge::FugaみたいなのをOKにするってこと？コメントで具体例つけとくと良さそう

2023-08-07 00:20 UTC, mzw86020424 commented on api/.rubocop.yml
> +  Enabled: false
これは早期リターンのことだと思うからあったほうがいいよ

2023-08-07 00:20 UTC, mzw86020424 commented on api/.rubocop.yml
> +  Enabled: false
これも厳格に判断した方がいいからあった方がいい

2023-08-07 00:20 UTC, mzw86020424 commented on api/.rubocop.yml
> +  Enabled: false
i18nの具体例がコメントにあると嬉しい

2023-08-07 00:20 UTC, mzw86020424 commented on api/.rubocop.yml
> +  Enabled: false
これなんで元々変更が0であることをテストしたらNGなのかが気になる

2023-08-07 01:01 UTC, tkm-mkzk commented on api/.rubocop.yml
> +  Enabled: false
@mzw86020424 
アプリケーションのソースコード内にハードコードされた文字列リテラルを検出し、それらを国際化のためのロケールファイルに移動させることを推奨させるもので、エラーメッセージとかをソースコードとかに直接記載すると違反がでます。ja.ymlとかにエラーメッセージ書いてそれを読み込むみたいな設定をしないとダメなやつです。
ただ、今回フロントは全部next.jsで記載するので、今回はいらなさそうなんで消します！

2023-08-07 01:04 UTC, tkm-mkzk commented on api/.rubocop.yml
> +  Enabled: false
@mzw86020424 
変わらないということをテストするコード、例えば下記
expect { some_method }.to change { object.attribute }.by(0)
これを下記のように書いてねっていうcop
expect { some_method }.not_to change { object.attribute }

これもいらなさそうなので、一旦削除します。

2023-08-08 23:42 UTC, mzw86020424 commented on api/.rubocop.yml
> +  Enabled: false
@tkm-mkzk 
なるほど！ありがとう、これだね。
https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsi18nlocaletexts

> ただ、今回フロントは全部next.jsで記載するので、今回はいらなさそうなんで消します！

バリデーションエラーのメッセージのこと？コードにベタ書きしがちなのってバリデーションメッセージ以外もあるし、そもそもエラーによってはバックエンド側でメッセージ作るケースもあると思うので、この制御はあった方がいいかとお思いました。

2023-08-09 00:30 UTC, mzw86020424 approved these changes

2023-08-09 00:41 UTC, merged