[wip]ホテル一覧の各列の調整と名前をリンクにして、url列を削除する/#82
mzw86020424/next-rakuten-app pull request #84
Opened 2023-08-09 00:27 UTC by tkm-mkzk

## イシュー番号
* Fix #82 

## やったこと
* ホテル一覧の各列の調整と名前をリンクにして、url列を削除する

## やらないこと
* なし

## できるようになること（ユーザ目線）
* ホテル名をクリックすると、ホテルサイトに遷移できる

## できなくなること（ユーザ目線）
* なし

## チェック項目
 - [ ] `npm run lint`でエラーがでないことを確認
 - [ ] `rubocop -A`で整形されたことを確認
 - [ ] `rspec`でテストが通ることを確認

## 動作確認
* 

## その他
*

2023-08-11 00:23 UTC, mzw86020424 requested changes
@tkm-mkzk 
コンフリクト解消お願いします:pray:

2023-08-13 00:56 UTC, tkm-mkzk commented
> @tkm-mkzk コンフリクトの解消お願いします🙏

@mzw86020424 解消しました！

2023-08-13 11:07 UTC, mzw86020424 requested changes
@tkm-mkzk 
文字列を入れてsearchすると以下エラーが出ました。
事前に何かしら準備が必要であれば教えてください！
![スクリーンショット 2023-08-13 19 57 59](https://github.com/mzw86020424/next-rakuten-app/assets/72555480/f1fc2270-8e24-427e-bb1b-2dd5e54a7dd9)

2023-08-13 11:07 UTC, mzw86020424 commented on frontend/pages/hotels.tsx
> +      <form
formタグを追加した理由を知りたいです:bear:

2023-08-13 11:07 UTC, mzw86020424 commented on frontend/__tests__/pages/hotels.tsx
> +  const performHotelSearch = async (searchValue = 'test') => {
itでなく関数に変更した理由を知りたいです:bear:

2023-08-13 23:12 UTC, tkm-mkzk commented on frontend/pages/hotels.tsx
> +      <form
@mzw86020424 
エンターボタンで検索を可能にするためです。

2023-08-13 23:15 UTC, tkm-mkzk commented on frontend/__tests__/pages/hotels.tsx
> +  const performHotelSearch = async (searchValue = 'test') => {
@mzw86020424 
変更はしてません。64行目にコード残ってます。

2023-08-13 23:19 UTC, tkm-mkzk commented
> @tkm-mkzk 文字列を入れてsearchすると以下エラーが出ました。 事前に何かしら準備が必要であれば教えてください！ ![スクリーンショット 2023-08-13 19 57 59](https://user-images.githubusercontent.com/72555480/260298570-f1fc2270-8e24-427e-bb1b-2dd5e54a7dd9.png)

@mzw86020424 
特に準備はないんですけどね、自分のとこだとそのエラーでないですね、、、
1回npm installしてみてもっかいやってみてもらえます？
あとエラー文章でもらえると助かります！

2023-08-13 23:25 UTC, mzw86020424 commented
> > @tkm-mkzk 文字列を入れてsearchすると以下エラーが出ました。 事前に何かしら準備が必要であれば教えてください！ ![スクリーンショット 2023-08-13 19 57 59](https://user-images.githubusercontent.com/72555480/260298570-f1fc2270-8e24-427e-bb1b-2dd5e54a7dd9.png)
> 
> @mzw86020424 特に準備はないんですけどね、自分のとこだとそのエラーでないですね、、、 1回npm installしてみてもっかいやってみてもらえます？ あとエラー文章でもらえると助かります！

@tkm-mkzk 
npm installしたら解消しました！npm intallなど必要な場合PRの`その他`とかに書いといてもらえると嬉しいです！俺も書き忘れる時あるけど！

2023-08-13 23:27 UTC, mzw86020424 commented on frontend/__tests__/pages/hotels.tsx
> +  const performHotelSearch = async (searchValue = 'test') => {
@tkm-mkzk 
失礼しました:bow:
関数に切り出した理由が知りたいです！

2023-08-13 23:27 UTC, tkm-mkzk commented
> > > @tkm-mkzk 文字列を入れてsearchすると以下エラーが出ました。 事前に何かしら準備が必要であれば教えてください！ ![スクリーンショット 2023-08-13 19 57 59](https://user-images.githubusercontent.com/72555480/260298570-f1fc2270-8e24-427e-bb1b-2dd5e54a7dd9.png)
> > 
> > 
> > @mzw86020424 特に準備はないんですけどね、自分のとこだとそのエラーでないですね、、、 1回npm installしてみてもっかいやってみてもらえます？ あとエラー文章でもらえると助かります！
> 
> @tkm-mkzk npm installしたら解消しました！npm intallなど必要な場合PRの`その他`とかに書いといてもらえると嬉しいです！俺も書き忘れる時あるけど！

@mzw86020424 
了解しました！！

2023-08-13 23:28 UTC, mzw86020424 commented on frontend/__tests__/pages/hotels.tsx
> +  const performHotelSearch = async (searchValue = 'test') => {
あ、共通化してるのか！

2023-08-13 23:32 UTC, mzw86020424 commented
@tkm-mkzk 
サムネ画像ちょっとでかいなと思います！それ以外はLGTMです！

> > > @tkm-mkzk 文字列を入れてsearchすると以下エラーが出ました。 事前に何かしら準備が必要であれば教えてください！ ![スクリーンショット 2023-08-13 19 57 59](https://user-images.githubusercontent.com/72555480/260298570-f1fc2270-8e24-427e-bb1b-2dd5e54a7dd9.png)
> > 
> > 
> > @mzw86020424 特に準備はないんですけどね、自分のとこだとそのエラーでないですね、、、 1回npm installしてみてもっかいやってみてもらえます？ あとエラー文章でもらえると助かります！
> 
> @tkm-mkzk npm installしたら解消しました！npm intallなど必要な場合PRの`その他`とかに書いといてもらえると嬉しいです！俺も書き忘れる時あるけど！

@tkm-mkzk 
ちなみになんでnpm installで解消するんだろうね、特にライブラリ追加してないよね？tailwindの機能使い始めると必要なのかな？

2023-08-13 23:33 UTC, mzw86020424 commented
@tkm-mkzk 
サムネ画像がちょっとでかいかも！それ以外はlgtmです！

2023-08-13 23:43 UTC, tkm-mkzk commented
> @tkm-mkzk サムネ画像ちょっとでかいなと思います！それ以外はLGTMです！
> 
> > > > @tkm-mkzk 文字列を入れてsearchすると以下エラーが出ました。 事前に何かしら準備が必要であれば教えてください！ ![スクリーンショット 2023-08-13 19 57 59](https://user-images.githubusercontent.com/72555480/260298570-f1fc2270-8e24-427e-bb1b-2dd5e54a7dd9.png)
> > > 
> > > 
> > > @mzw86020424 特に準備はないんですけどね、自分のとこだとそのエラーでないですね、、、 1回npm installしてみてもっかいやってみてもらえます？ あとエラー文章でもらえると助かります！
> > 
> > 
> > @tkm-mkzk npm installしたら解消しました！npm intallなど必要な場合PRの`その他`とかに書いといてもらえると嬉しいです！俺も書き忘れる時あるけど！
> 
> @tkm-mkzk ちなみになんでnpm installで解消するんだろうね、特にライブラリ追加してないよね？tailwindの機能使い始めると必要なのかな？

@mzw86020424 
確かに！謎ですね、、npm install関係なくて、dockerとかの関係の可能性もありますね！

2023-08-13 23:44 UTC, tkm-mkzk commented
> @tkm-mkzk サムネ画像がちょっとでかいかも！それ以外はlgtmです！

@mzw86020424 
了解です！ここだけ少し小さくします！

2023-08-27 05:13 UTC, mzw86020424 approved these changes

2023-08-27 05:13 UTC, merged